apiVersion: v1
kind: Service
metadata:
  name: sms-server
spec:
  type: NodePort  # Exposes the service on <NodeIP>:<randomPort> for now
  selector:
    app: sms-server
  ports:
    - port: 4000
      targetPort: 4000
